// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Drawing;
using System.IO;
using System.Threading.Tasks;
using System.Windows.Media;
using System.Windows.Media.Imaging;

namespace Hetfield.Entities;

public partial class CarPhotos
{

    public int IdCar { get; set; }

    public int IdPhoto { get; set; }

    public byte[] Photo { get; set; }

    public virtual Cars IdCarNavigation { get; set; }

}