// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hetfield.Entities;

public partial class CarsPassport
{
    public int IdCarPassport { get; set; }

    public int CarManufactureYear { get; set; }

    public int IdCarType { get; set; }

    public int IdCarColor { get; set; }

    public int IdOwner { get; set; }

    public string CarModel { get; set; }

    public string VinNumber { get; set; }

    public int CarPower { get; set; }

    public int EngineDisplacement { get; set; }

    public string PassportSeriasAndNumber { get; set; }

    public DateTime DateOfIssue { get; set; }

    public virtual ManufactureYears CarManufactureYearNavigation { get; set; }

    public virtual ICollection<Cars> Cars { get; set; } = new List<Cars>();

    public virtual CarColors IdCarColorNavigation { get; set; }

    public virtual CarTypes IdCarTypeNavigation { get; set; }

    public virtual Users IdOwnerNavigation { get; set; }
}