// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Windows.Media;

namespace Hetfield.Entities;

public partial class Cars
{
    public int IdCar { get; set; }

    public int IdCarPassport { get; set; }

    public int IdTranssmission { get; set; }

    public int IdEngine { get; set; }

    public int IdCarConfiguration { get; set; }

    public int IdCarStatus { get; set; }

    public decimal Price { get; set; }

    public int Mileage { get; set; }

    public string Description { get; set; }

    public string CarNumber { get; set; }

    public int TankCapacity { get; set; }

    public virtual ICollection<CarPhotos> CarPhotos { get; set; } = new List<CarPhotos>();

    public virtual CarConfigurations IdCarConfigurationNavigation { get; set; }

    public virtual CarsPassport IdCarPassportNavigation { get; set; }

    public virtual CarStatuses IdCarStatusNavigation { get; set; }

    public virtual CarEngines IdEngineNavigation { get; set; }

    public virtual CarTranssmissions IdTranssmissionNavigation { get; set; }

    public virtual ICollection<Orders> Orders { get; set; } = new List<Orders>();

    public override string ToString()
    {
        return "Mercedez-Benz " + IdCarPassportNavigation.CarModel
                + " " + IdCarPassportNavigation.VinNumber + " " +
                IdCarStatusNavigation.CarStatusName + " " +
                IdCarPassportNavigation.IdOwnerNavigation.Surname + " " +
                IdCarPassportNavigation.IdOwnerNavigation.Name + " " +
                IdCarPassportNavigation.IdOwnerNavigation.Patronymic + " " +
                IdCarPassportNavigation.IdOwnerNavigation.PhoneNumber;
    }
}