// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hetfield.Entities;

public partial class CarTypes
{
    public int IdCarType { get; set; }

    public string TypeName { get; set; }

    public virtual ICollection<CarsPassport> CarsPassport { get; set; } = new List<CarsPassport>();

    public override string ToString()
    {
        return TypeName;
    }
}