// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hetfield.Entities;

public partial class Genders
{
    public int IdGender { get; set; }

    public string GenderName { get; set; }

    public virtual ICollection<Users> Users { get; set; } = new List<Users>();

    public override string ToString()
    {
        return GenderName;
    }
}