// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hetfield.Entities;

public partial class Orders
{
    public int IdOrder { get; set; }

    public int IdBuyer { get; set; }

    public int IdCar { get; set; }

    public int IdStaff { get; set; }

    public int IdOrderStatus { get; set; }

    public DateTime DateOfOrder { get; set; }

    public decimal FinalPrice { get; set; }

    public virtual Users IdBuyerNavigation { get; set; }

    public virtual Cars IdCarNavigation { get; set; }

    public virtual OrderStatuses IdOrderStatusNavigation { get; set; }

    public virtual Users IdStaffNavigation { get; set; }

    public override string ToString()
    {
        return IdBuyerNavigation.Surname + " " +
               IdBuyerNavigation.Name + " " +
               IdBuyerNavigation.Patronymic + " " +
               IdCarNavigation.CarNumber + " " +
               IdCarNavigation.IdCarPassportNavigation.CarModel + " " +
               IdStaffNavigation.Surname + " " +
               IdStaffNavigation.Name + " " +
               IdStaffNavigation.Patronymic + " " +
               IdCarNavigation.IdCarPassportNavigation.IdOwnerNavigation.Surname + " " +
               IdCarNavigation.IdCarPassportNavigation.IdOwnerNavigation.Name + " " +
               IdCarNavigation.IdCarPassportNavigation.IdOwnerNavigation.Patronymic + " " +
               $"{DateOfOrder:d}" + " " +
               FinalPrice + " " +
               IdOrderStatusNavigation.OrderStatusName;
    }
}