// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hetfield.Entities;

public partial class OrderStatuses
{
    public int IdOrderStatus { get; set; }

    public string OrderStatusName { get; set; }

    public virtual ICollection<Orders> Orders { get; set; } = new List<Orders>();

    public override string ToString()
    {
        return OrderStatusName;
    }
}