// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hetfield.Entities;

public partial class Users
{
    public int IdUser { get; set; }

    public string Surname { get; set; }

    public string Name { get; set; }

    public string Patronymic { get; set; }

    public DateTime DateOfBirth { get; set; }

    public string PhoneNumber { get; set; }

    public string Email { get; set; }

    public string Login { get; set; }

    public string Password { get; set; }

    public byte[] Photo { get; set; }

    public int IdRole { get; set; }

    public int IdGender { get; set; }

    public virtual ICollection<CarsPassport> CarsPassport { get; set; } = new List<CarsPassport>();

    public virtual Genders IdGenderNavigation { get; set; }

    public virtual Roles IdRoleNavigation { get; set; }

    public virtual ICollection<Orders> OrdersIdBuyerNavigation { get; set; } = new List<Orders>();

    public virtual ICollection<Orders> OrdersIdStaffNavigation { get; set; } = new List<Orders>();

    public override string ToString()
    {
        return this.Surname + " " +
                this.Name + " " +
                this.Patronymic + " " +
                $"{this.DateOfBirth:d}" + " " +
                this.PhoneNumber + " " +
                this.Email + " " +
                this.Login + " " +
                this.Password + " " +
                this.IdRoleNavigation.RoleName + " " +
                this.IdGenderNavigation.GenderName;
    }
}